; Overdrive Core - Assembled Mech Configuration
; Automatically saved when assembling in Garage

[Weapons]
RightArm=RF-024
LeftArm=EN-010
RightBack=ML-080
LeftBack=PL-040

[Frame]
Head=HD-012
Core=CR-020
Arms=AM-030
Legs=LG-040

[Internal]
Booster=BST-010
FCS=FCS-010
Generator=GEN-010
